version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: payments_admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: