services:
  postgres:
    image: postgres:15-alpine
    container_name: payment_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: payments_admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d payments_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis: 
    image: redis:alpine
    container_name: payment_redis
    ports:
      - "6379:6379"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: dockerfile
    container_name: payment_service
    environment:
      DATABASE_URL: "postgresql://admin:123456789@postgres:5432/payments_admin?schema=public"
      REDIS_HOST: redis 
      PORT: 3001
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3001:3001"

  notification-service: 
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification_service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://admin:123456789@postgres:5432/payments_admin?schema=public
      - PORT=3002
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "3002:3002"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: dockerfile
    container_name: api_gateway
    environment:
      PORT: 3000
      PAYMENT_SERVICE_URL: http://payment-service:3001/api/v1
      JWT_SECRET: PRUEBA_TECNICA_SECRET_KEY
    depends_on:
      - payment-service
    ports:
      - "3000:3000"

volumes:
  postgres_data: